export const supportedLocales = [
  "en",
  "es",
  "fr",
  "de",
  "it",
  "nl",
  "pt-BR",
  "pt-PT",
  "pl",
  "sv",
  "tr",
  "ar",
  "he",
  "ru",
  "ja",
  "ko",
  "zh-Hans",
  "zh-Hant",
  "hi",
  "id",
] as const;

export type SupportedLocale = (typeof supportedLocales)[number];

export const rtlLocales = ["ar", "he"] as const;

const enCopy = {
  countdownLabel: "Limited Time Offer",
  countdownHourShort: "H",
  countdownMinuteShort: "M",
  countdownSecondShort: "S",
  heroModelMavic4: "KIT DJI MAVIC 4 PRO FLY",
  heroModelMavic3: "KIT DJI MAVIC 3 PRO FLY",
  heroTitle: "Complete DJI Drone Kit at a ridiculous price.",
  heroSubtitle:
    "With the launch of the new global lineup, older inventory is now being released.",
  heroFeatureLine: "BAG, PROPELLERS, GUARDS, CABLES AND BATTERY.",
  ctaGetMyDrone: "GET MY DRONE",
  carouselGoToImage: "Go to image",
  kitImageAlt: "DJI Mavic kit items",
  kitTitle: "What Comes in the Kit",
  kitBody:
    "You receive a complete bundle designed to come out of the box and fly with ease from the very first use.",
  kitItemDrone: "DJI Mavic Drone (3 Pro or 4 Pro)",
  kitItemController: "Smart remote controller",
  kitItemBattery: "1 long-lasting battery",
  kitItemPropellers: "Extra propellers and guards",
  kitItemCables: "Charging cables",
  kitItemBag: "Premium bag + integrated gimbal",
  comparisonHeadingLead: "Comparison",
  comparisonHeadingRest: "between the DJI Mavic 4 Pro and 3 Pro",
  comparisonSubtitle: "The new-generation leap in range and charging.",
  metricFlightRange: "Flight Range",
  metricChargingThree: "Charging Time (3 Batteries)",
  metricChargingOne: "Charging (1 Battery)",
  modelMavic4: "Mavic 4 Pro",
  modelMavic3: "Mavic 3 Pro",
  upTo41Km: "up to 41km",
  upTo28Km: "up to 28km",
  minutes90: "90 min",
  minutes210: "210 min",
  minutes51: "51 min",
  minutes70: "70 min",
  chooseModelTitle: "Choose Your Model",
  chooseModelSubtitle: "Complete kit ready to fly. Free shipping.",
  productBadge: "Kit Fly More",
  completeKit: "Complete Kit",
  topicController: "Controller",
  topicBag: "Bag",
  topicPropellers: "Propellers",
  topicGuards: "Guards",
  topicCables: "Cables",
  topicBattery: "Battery",
  freeShipping: "Free Shipping",
  limitedStock: "Limited Stock",
  faqTitle: "Frequently Asked Questions",
  faqShippingQ: "How long does delivery take?",
  faqShippingA:
    "Shipping is free and the average delivery time is 7 to 15 business days, depending on your location.",
  faqPriceQ: "Why is the price so low?",
  faqPriceA:
    "With the launch of DJI's new global lineup, current-generation inventory is being cleared out. We use direct distributor agreements to offer prices below market value.",
  faqReturnQ: "Can I return it if I do not like it?",
  faqReturnA:
    "Yes. You have 30 days to return the product at no cost and receive a full refund, no questions asked.",
  faqDifferenceQ: "What is the difference between the Mavic 3 Pro and 4 Pro?",
  faqDifferenceA:
    "The Mavic 4 Pro has a flight range of up to 41 km (vs. 28 km), charges 3 batteries in 90 min (vs. 210 min), and includes an upgraded image sensor with higher resolution.",
  footerSeries: "Mavic Pro Series",
  privacy: "Privacy",
  terms: "Terms",
  contact: "Contact",
  disclaimer:
    "This site is not affiliated with or endorsed by DJI. Product names and images are used for identification purposes only.",
} as const;

type CopyKey = keyof typeof enCopy;
type CopyCatalog = Record<CopyKey, string>;

const localeOverrides: Partial<Record<SupportedLocale, Partial<CopyCatalog>>> = {
  "pt-BR": {
    countdownLabel: "Oferta por Tempo Limitado",
    countdownHourShort: "H",
    countdownMinuteShort: "M",
    countdownSecondShort: "S",
    heroModelMavic4: "KIT DJI MAVIC 4 PRO FLY",
    heroModelMavic3: "KIT DJI MAVIC 3 PRO FLY",
    heroTitle: "Kit completo de drone DJI por um preço absurdo.",
    heroSubtitle:
      "Com o lançamento da nova linha global, o estoque da geração anterior está sendo liberado.",
    heroFeatureLine: "BOLSA, HÉLICES, PROTETORES, CABOS E BATERIA.",
    ctaGetMyDrone: "PEGAR MEU DRONE",
    carouselGoToImage: "Ir para a imagem",
    kitImageAlt: "Itens do kit DJI Mavic",
    kitTitle: "O Que Vem no Kit",
    kitBody:
      "Você recebe um pacote completo, pronto para sair da caixa e voar com facilidade desde o primeiro uso.",
    kitItemDrone: "Drone DJI Mavic (3 Pro ou 4 Pro)",
    kitItemController: "Controle remoto inteligente",
    kitItemBattery: "1 bateria de longa duração",
    kitItemPropellers: "Hélices extras e protetores",
    kitItemCables: "Cabos de carregamento",
    kitItemBag: "Bolsa premium + gimbal integrado",
    comparisonHeadingLead: "Comparação",
    comparisonHeadingRest: "entre o DJI Mavic 4 Pro e o 3 Pro",
    comparisonSubtitle: "O salto da nova geração em alcance e carregamento.",
    metricFlightRange: "Alcance de Voo",
    metricChargingThree: "Tempo de Carga (3 Baterias)",
    metricChargingOne: "Carga (1 Bateria)",
    upTo41Km: "até 41km",
    upTo28Km: "até 28km",
    chooseModelTitle: "Escolha Seu Modelo",
    chooseModelSubtitle: "Kit completo pronto para voar. Frete grátis.",
    productBadge: "Kit Fly More",
    completeKit: "Kit Completo",
    topicController: "Controle",
    topicBag: "Bolsa",
    topicPropellers: "Hélices",
    topicGuards: "Protetores",
    topicCables: "Cabos",
    topicBattery: "Bateria",
    freeShipping: "Frete Grátis",
    limitedStock: "Estoque Limitado",
    faqTitle: "Perguntas Frequentes",
    faqShippingQ: "Quanto tempo demora a entrega?",
    faqShippingA:
      "O frete é grátis e o prazo médio de entrega é de 7 a 15 dias úteis, dependendo da sua localização.",
    faqPriceQ: "Por que o preço está tão baixo?",
    faqPriceA:
      "Com o lançamento da nova linha global da DJI, o estoque da geração atual está sendo liquidado. Usamos acordos diretos com distribuidores para oferecer preços abaixo do mercado.",
    faqReturnQ: "Posso devolver se eu não gostar?",
    faqReturnA:
      "Sim. Você tem 30 dias para devolver o produto sem custo e receber reembolso total, sem perguntas.",
    faqDifferenceQ: "Qual é a diferença entre o Mavic 3 Pro e o 4 Pro?",
    faqDifferenceA:
      "O Mavic 4 Pro tem alcance de voo de até 41 km (contra 28 km), carrega 3 baterias em 90 min (contra 210 min) e inclui um sensor de imagem aprimorado com maior resolução.",
    footerSeries: "Série Mavic Pro",
    privacy: "Privacidade",
    terms: "Termos",
    contact: "Contato",
    disclaimer:
      "Este site não é afiliado nem endossado pela DJI. Nomes e imagens de produtos são usados apenas para identificação.",
  },
  "pt-PT": {
    countdownLabel: "Oferta por Tempo Limitado",
    heroTitle: "Kit completo de drone DJI por um preço inacreditável.",
    heroSubtitle:
      "Com o lançamento da nova gama global, o stock da geração anterior está agora a ser disponibilizado.",
    heroFeatureLine: "MALA, HÉLICES, PROTETORES, CABOS E BATERIA.",
    ctaGetMyDrone: "OBTER O MEU DRONE",
    carouselGoToImage: "Ir para a imagem",
    kitImageAlt: "Itens do kit DJI Mavic",
    kitTitle: "O Que Vem no Kit",
    kitBody:
      "Recebe um conjunto completo, pronto para sair da caixa e voar com facilidade desde a primeira utilização.",
    kitItemDrone: "Drone DJI Mavic (3 Pro ou 4 Pro)",
    kitItemController: "Comando inteligente",
    kitItemBattery: "1 bateria de longa duração",
    kitItemPropellers: "Hélices extra e protetores",
    kitItemCables: "Cabos de carregamento",
    kitItemBag: "Mala premium + gimbal integrado",
    comparisonHeadingLead: "Comparação",
    comparisonHeadingRest: "entre o DJI Mavic 4 Pro e o 3 Pro",
    comparisonSubtitle: "O salto da nova geração em alcance e carregamento.",
    metricFlightRange: "Alcance de Voo",
    metricChargingThree: "Tempo de Carga (3 Baterias)",
    metricChargingOne: "Carga (1 Bateria)",
    upTo41Km: "até 41km",
    upTo28Km: "até 28km",
    chooseModelTitle: "Escolha o Seu Modelo",
    chooseModelSubtitle: "Kit completo pronto a voar. Envio grátis.",
    productBadge: "Kit Fly More",
    completeKit: "Kit Completo",
    topicController: "Comando",
    topicBag: "Mala",
    topicPropellers: "Hélices",
    topicGuards: "Protetores",
    topicCables: "Cabos",
    topicBattery: "Bateria",
    freeShipping: "Envio Grátis",
    limitedStock: "Stock Limitado",
    faqTitle: "Perguntas Frequentes",
    faqShippingQ: "Quanto tempo demora a entrega?",
    faqShippingA:
      "O envio é grátis e o prazo médio de entrega é de 7 a 15 dias úteis, dependendo da sua localização.",
    faqPriceQ: "Porque é que o preço é tão baixo?",
    faqPriceA:
      "Com o lançamento da nova gama global da DJI, o stock da geração atual está a ser escoado. Usamos acordos diretos com distribuidores para oferecer preços abaixo do mercado.",
    faqReturnQ: "Posso devolver se não gostar?",
    faqReturnA:
      "Sim. Tem 30 dias para devolver o produto sem custos e receber o reembolso total, sem perguntas.",
    faqDifferenceQ: "Qual é a diferença entre o Mavic 3 Pro e o 4 Pro?",
    faqDifferenceA:
      "O Mavic 4 Pro tem alcance de voo até 41 km (contra 28 km), carrega 3 baterias em 90 min (contra 210 min) e inclui um sensor de imagem melhorado com maior resolução.",
    footerSeries: "Série Mavic Pro",
    privacy: "Privacidade",
    terms: "Termos",
    contact: "Contacto",
    disclaimer:
      "Este site não é afiliado nem endossado pela DJI. Os nomes e imagens dos produtos são usados apenas para identificação.",
  },
  es: {
    countdownLabel: "Oferta por Tiempo Limitado",
    heroTitle: "Kit completo de dron DJI a un precio ridículo.",
    heroSubtitle:
      "Con el lanzamiento de la nueva línea global, el inventario anterior se está liberando.",
    heroFeatureLine: "BOLSA, HÉLICES, PROTECTORES, CABLES Y BATERÍA.",
    ctaGetMyDrone: "CONSEGUIR MI DRON",
    carouselGoToImage: "Ir a la imagen",
    kitImageAlt: "Artículos del kit DJI Mavic",
    kitTitle: "Qué Incluye el Kit",
    kitBody:
      "Recibes un paquete completo diseñado para salir de la caja y volar con facilidad desde el primer uso.",
    kitItemDrone: "Dron DJI Mavic (3 Pro o 4 Pro)",
    kitItemController: "Control remoto inteligente",
    kitItemBattery: "1 batería de larga duración",
    kitItemPropellers: "Hélices extra y protectores",
    kitItemCables: "Cables de carga",
    kitItemBag: "Bolsa premium + gimbal integrado",
    comparisonHeadingLead: "Comparación",
    comparisonHeadingRest: "entre el DJI Mavic 4 Pro y el 3 Pro",
    comparisonSubtitle: "El salto de nueva generación en alcance y carga.",
    metricFlightRange: "Alcance de Vuelo",
    metricChargingThree: "Tiempo de Carga (3 Baterías)",
    metricChargingOne: "Carga (1 Batería)",
    upTo41Km: "hasta 41km",
    upTo28Km: "hasta 28km",
    chooseModelTitle: "Elige Tu Modelo",
    chooseModelSubtitle: "Kit completo listo para volar. Envío gratis.",
    productBadge: "Kit Fly More",
    completeKit: "Kit Completo",
    topicController: "Control",
    topicBag: "Bolsa",
    topicPropellers: "Hélices",
    topicGuards: "Protectores",
    topicCables: "Cables",
    topicBattery: "Batería",
    freeShipping: "Envío Gratis",
    limitedStock: "Stock Limitado",
    faqTitle: "Preguntas Frecuentes",
    faqShippingQ: "¿Cuánto tarda la entrega?",
    faqShippingA:
      "El envío es gratis y el tiempo medio de entrega es de 7 a 15 días hábiles, según tu ubicación.",
    faqPriceQ: "¿Por qué el precio es tan bajo?",
    faqPriceA:
      "Con el lanzamiento de la nueva línea global de DJI, el inventario de generación actual se está liquidando. Usamos acuerdos directos con distribuidores para ofrecer precios por debajo del mercado.",
    faqReturnQ: "¿Puedo devolverlo si no me gusta?",
    faqReturnA:
      "Sí. Tienes 30 días para devolver el producto sin costo y recibir un reembolso completo, sin preguntas.",
    faqDifferenceQ: "¿Cuál es la diferencia entre el Mavic 3 Pro y el 4 Pro?",
    faqDifferenceA:
      "El Mavic 4 Pro tiene un alcance de vuelo de hasta 41 km (frente a 28 km), carga 3 baterías en 90 min (frente a 210 min) e incluye un sensor de imagen mejorado con mayor resolución.",
    footerSeries: "Serie Mavic Pro",
    privacy: "Privacidad",
    terms: "Términos",
    contact: "Contacto",
    disclaimer:
      "Este sitio no está afiliado ni respaldado por DJI. Los nombres e imágenes de productos se usan solo con fines de identificación.",
  },
  fr: {
    countdownLabel: "Offre à Durée Limitée",
    heroTitle: "Kit drone DJI complet à un prix incroyable.",
    heroSubtitle:
      "Avec le lancement de la nouvelle gamme mondiale, les anciens stocks sont maintenant libérés.",
    heroFeatureLine: "SAC, HÉLICES, PROTECTIONS, CÂBLES ET BATTERIE.",
    ctaGetMyDrone: "OBTENIR MON DRONE",
    carouselGoToImage: "Aller à l'image",
    kitImageAlt: "Éléments du kit DJI Mavic",
    kitTitle: "Ce Que Contient le Kit",
    kitBody:
      "Vous recevez un ensemble complet conçu pour sortir de la boîte et voler facilement dès la première utilisation.",
    kitItemDrone: "Drone DJI Mavic (3 Pro ou 4 Pro)",
    kitItemController: "Télécommande intelligente",
    kitItemBattery: "1 batterie longue durée",
    kitItemPropellers: "Hélices et protections supplémentaires",
    kitItemCables: "Câbles de charge",
    kitItemBag: "Sac premium + nacelle intégrée",
    comparisonHeadingLead: "Comparaison",
    comparisonHeadingRest: "entre le DJI Mavic 4 Pro et le 3 Pro",
    comparisonSubtitle: "Le saut de nouvelle génération en portée et en charge.",
    metricFlightRange: "Portée de Vol",
    metricChargingThree: "Temps de Charge (3 Batteries)",
    metricChargingOne: "Charge (1 Batterie)",
    upTo41Km: "jusqu'à 41km",
    upTo28Km: "jusqu'à 28km",
    chooseModelTitle: "Choisissez Votre Modèle",
    chooseModelSubtitle: "Kit complet prêt à voler. Livraison gratuite.",
    productBadge: "Kit Fly More",
    completeKit: "Kit Complet",
    topicController: "Télécommande",
    topicBag: "Sac",
    topicPropellers: "Hélices",
    topicGuards: "Protections",
    topicCables: "Câbles",
    topicBattery: "Batterie",
    freeShipping: "Livraison Gratuite",
    limitedStock: "Stock Limité",
    faqTitle: "Questions Fréquentes",
    faqShippingQ: "Combien de temps prend la livraison ?",
    faqShippingA:
      "La livraison est gratuite et le délai moyen est de 7 à 15 jours ouvrables, selon votre localisation.",
    faqPriceQ: "Pourquoi le prix est-il si bas ?",
    faqPriceA:
      "Avec le lancement de la nouvelle gamme mondiale de DJI, les stocks de génération actuelle sont écoulés. Nous utilisons des accords directs avec les distributeurs pour proposer des prix inférieurs au marché.",
    faqReturnQ: "Puis-je le retourner si je ne l'aime pas ?",
    faqReturnA:
      "Oui. Vous avez 30 jours pour retourner le produit sans frais et recevoir un remboursement complet, sans question.",
    faqDifferenceQ: "Quelle est la différence entre le Mavic 3 Pro et le 4 Pro ?",
    faqDifferenceA:
      "Le Mavic 4 Pro offre une portée de vol allant jusqu'à 41 km (contre 28 km), charge 3 batteries en 90 min (contre 210 min) et inclut un capteur d'image amélioré avec une résolution supérieure.",
    footerSeries: "Série Mavic Pro",
    privacy: "Confidentialité",
    terms: "Conditions",
    contact: "Contact",
    disclaimer:
      "Ce site n'est pas affilié à DJI ni approuvé par DJI. Les noms et images de produits sont utilisés uniquement à des fins d'identification.",
  },
  de: {
    countdownLabel: "Zeitlich Begrenztes Angebot",
    heroTitle: "Komplettes DJI-Drohnenkit zu einem unglaublichen Preis.",
    heroSubtitle:
      "Mit dem Start der neuen globalen Produktlinie wird älterer Bestand jetzt freigegeben.",
    heroFeatureLine: "TASCHE, PROPELLER, SCHUTZTEILE, KABEL UND AKKU.",
    ctaGetMyDrone: "MEINE DROHNE SICHERN",
    carouselGoToImage: "Zum Bild wechseln",
    kitImageAlt: "DJI Mavic Kit-Teile",
    kitTitle: "Was im Kit Enthalten Ist",
    kitBody:
      "Sie erhalten ein komplettes Set, das direkt nach dem Auspacken einfach flugbereit ist.",
    kitItemDrone: "DJI Mavic Drohne (3 Pro oder 4 Pro)",
    kitItemController: "Intelligente Fernsteuerung",
    kitItemBattery: "1 langlebiger Akku",
    kitItemPropellers: "Zusätzliche Propeller und Schutzteile",
    kitItemCables: "Ladekabel",
    kitItemBag: "Premium-Tasche + integrierter Gimbal",
    comparisonHeadingLead: "Vergleich",
    comparisonHeadingRest: "zwischen DJI Mavic 4 Pro und 3 Pro",
    comparisonSubtitle: "Der Sprung der neuen Generation bei Reichweite und Laden.",
    metricFlightRange: "Flugreichweite",
    metricChargingThree: "Ladezeit (3 Akkus)",
    metricChargingOne: "Laden (1 Akku)",
    upTo41Km: "bis zu 41km",
    upTo28Km: "bis zu 28km",
    chooseModelTitle: "Wählen Sie Ihr Modell",
    chooseModelSubtitle: "Komplettes flugbereites Kit. Kostenloser Versand.",
    productBadge: "Kit Fly More",
    completeKit: "Komplettes Kit",
    topicController: "Controller",
    topicBag: "Tasche",
    topicPropellers: "Propeller",
    topicGuards: "Schutzteile",
    topicCables: "Kabel",
    topicBattery: "Akku",
    freeShipping: "Kostenloser Versand",
    limitedStock: "Begrenzter Bestand",
    faqTitle: "Häufige Fragen",
    faqShippingQ: "Wie lange dauert die Lieferung?",
    faqShippingA:
      "Der Versand ist kostenlos und die durchschnittliche Lieferzeit beträgt je nach Standort 7 bis 15 Werktage.",
    faqPriceQ: "Warum ist der Preis so niedrig?",
    faqPriceA:
      "Mit dem Start der neuen globalen DJI-Produktlinie wird aktueller Bestand abverkauft. Durch direkte Händlervereinbarungen können wir Preise unter Marktwert anbieten.",
    faqReturnQ: "Kann ich es zurückgeben, wenn es mir nicht gefällt?",
    faqReturnA:
      "Ja. Sie haben 30 Tage Zeit, das Produkt kostenlos zurückzugeben und eine vollständige Rückerstattung zu erhalten, ohne Fragen.",
    faqDifferenceQ: "Was ist der Unterschied zwischen Mavic 3 Pro und 4 Pro?",
    faqDifferenceA:
      "Die Mavic 4 Pro hat eine Flugreichweite von bis zu 41 km (statt 28 km), lädt 3 Akkus in 90 min (statt 210 min) und enthält einen verbesserten Bildsensor mit höherer Auflösung.",
    footerSeries: "Mavic Pro Serie",
    privacy: "Datenschutz",
    terms: "Bedingungen",
    contact: "Kontakt",
    disclaimer:
      "Diese Website ist nicht mit DJI verbunden und wird nicht von DJI unterstützt. Produktnamen und Bilder dienen nur der Identifikation.",
  },
  it: {
    countdownLabel: "Offerta a Tempo Limitato",
    heroTitle: "Kit drone DJI completo a un prezzo incredibile.",
    heroSubtitle:
      "Con il lancio della nuova gamma globale, le scorte precedenti sono ora disponibili.",
    heroFeatureLine: "BORSA, ELICHE, PROTEZIONI, CAVI E BATTERIA.",
    ctaGetMyDrone: "PRENDI IL MIO DRONE",
    carouselGoToImage: "Vai all'immagine",
    kitImageAlt: "Elementi del kit DJI Mavic",
    kitTitle: "Cosa C'è nel Kit",
    kitBody:
      "Ricevi un pacchetto completo progettato per uscire dalla scatola e volare facilmente fin dal primo utilizzo.",
    kitItemDrone: "Drone DJI Mavic (3 Pro o 4 Pro)",
    kitItemController: "Radiocomando intelligente",
    kitItemBattery: "1 batteria a lunga durata",
    kitItemPropellers: "Eliche extra e protezioni",
    kitItemCables: "Cavi di ricarica",
    kitItemBag: "Borsa premium + gimbal integrato",
    comparisonHeadingLead: "Confronto",
    comparisonHeadingRest: "tra DJI Mavic 4 Pro e 3 Pro",
    comparisonSubtitle: "Il salto di nuova generazione in autonomia e ricarica.",
    metricFlightRange: "Portata di Volo",
    metricChargingThree: "Tempo di Ricarica (3 Batterie)",
    metricChargingOne: "Ricarica (1 Batteria)",
    upTo41Km: "fino a 41km",
    upTo28Km: "fino a 28km",
    chooseModelTitle: "Scegli il Tuo Modello",
    chooseModelSubtitle: "Kit completo pronto al volo. Spedizione gratuita.",
    productBadge: "Kit Fly More",
    completeKit: "Kit Completo",
    topicController: "Controller",
    topicBag: "Borsa",
    topicPropellers: "Eliche",
    topicGuards: "Protezioni",
    topicCables: "Cavi",
    topicBattery: "Batteria",
    freeShipping: "Spedizione Gratuita",
    limitedStock: "Scorte Limitate",
    faqTitle: "Domande Frequenti",
    faqShippingQ: "Quanto tempo richiede la consegna?",
    faqShippingA:
      "La spedizione è gratuita e il tempo medio di consegna è da 7 a 15 giorni lavorativi, in base alla tua posizione.",
    faqPriceQ: "Perché il prezzo è così basso?",
    faqPriceA:
      "Con il lancio della nuova gamma globale DJI, le scorte della generazione attuale vengono liquidate. Usiamo accordi diretti con i distributori per offrire prezzi sotto il valore di mercato.",
    faqReturnQ: "Posso restituirlo se non mi piace?",
    faqReturnA:
      "Sì. Hai 30 giorni per restituire il prodotto senza costi e ricevere un rimborso completo, senza domande.",
    faqDifferenceQ: "Qual è la differenza tra Mavic 3 Pro e 4 Pro?",
    faqDifferenceA:
      "Il Mavic 4 Pro ha una portata di volo fino a 41 km (contro 28 km), ricarica 3 batterie in 90 min (contro 210 min) e include un sensore immagine aggiornato con risoluzione più alta.",
    footerSeries: "Serie Mavic Pro",
    privacy: "Privacy",
    terms: "Termini",
    contact: "Contatto",
    disclaimer:
      "Questo sito non è affiliato né approvato da DJI. Nomi e immagini dei prodotti sono usati solo a scopo identificativo.",
  },
  nl: {
    countdownLabel: "Tijdelijke Aanbieding",
    heroTitle: "Complete DJI-dronekit voor een ongelooflijke prijs.",
    heroSubtitle:
      "Door de lancering van de nieuwe wereldwijde lijn wordt oudere voorraad nu vrijgegeven.",
    heroFeatureLine: "TAS, PROPELLERS, BESCHERMERS, KABELS EN BATTERIJ.",
    ctaGetMyDrone: "PAK MIJN DRONE",
    carouselGoToImage: "Ga naar afbeelding",
    kitImageAlt: "DJI Mavic kitonderdelen",
    kitTitle: "Wat Zit er in de Kit",
    kitBody:
      "Je ontvangt een complete bundel die direct uit de doos gemakkelijk klaar is om te vliegen.",
    kitItemDrone: "DJI Mavic-drone (3 Pro of 4 Pro)",
    kitItemController: "Slimme afstandsbediening",
    kitItemBattery: "1 batterij met lange levensduur",
    kitItemPropellers: "Extra propellers en beschermers",
    kitItemCables: "Laadkabels",
    kitItemBag: "Premium tas + geïntegreerde gimbal",
    comparisonHeadingLead: "Vergelijking",
    comparisonHeadingRest: "tussen de DJI Mavic 4 Pro en 3 Pro",
    comparisonSubtitle: "De sprong van de nieuwe generatie in bereik en laden.",
    metricFlightRange: "Vliegbereik",
    metricChargingThree: "Laadtijd (3 Batterijen)",
    metricChargingOne: "Laden (1 Batterij)",
    upTo41Km: "tot 41km",
    upTo28Km: "tot 28km",
    chooseModelTitle: "Kies Je Model",
    chooseModelSubtitle: "Complete kit klaar om te vliegen. Gratis verzending.",
    productBadge: "Kit Fly More",
    completeKit: "Complete Kit",
    topicController: "Controller",
    topicBag: "Tas",
    topicPropellers: "Propellers",
    topicGuards: "Beschermers",
    topicCables: "Kabels",
    topicBattery: "Batterij",
    freeShipping: "Gratis Verzending",
    limitedStock: "Beperkte Voorraad",
    faqTitle: "Veelgestelde Vragen",
    faqShippingQ: "Hoe lang duurt de levering?",
    faqShippingA:
      "Verzending is gratis en de gemiddelde levertijd is 7 tot 15 werkdagen, afhankelijk van je locatie.",
    faqPriceQ: "Waarom is de prijs zo laag?",
    faqPriceA:
      "Door de lancering van DJI's nieuwe wereldwijde lijn wordt voorraad van de huidige generatie uitverkocht. We gebruiken directe distributeursovereenkomsten om prijzen onder marktwaarde aan te bieden.",
    faqReturnQ: "Kan ik het retourneren als ik het niet leuk vind?",
    faqReturnA:
      "Ja. Je hebt 30 dagen om het product gratis te retourneren en een volledige terugbetaling te ontvangen, zonder vragen.",
    faqDifferenceQ: "Wat is het verschil tussen de Mavic 3 Pro en 4 Pro?",
    faqDifferenceA:
      "De Mavic 4 Pro heeft een vliegbereik tot 41 km (tegenover 28 km), laadt 3 batterijen in 90 min (tegenover 210 min) en bevat een verbeterde beeldsensor met hogere resolutie.",
    footerSeries: "Mavic Pro-serie",
    privacy: "Privacy",
    terms: "Voorwaarden",
    contact: "Contact",
    disclaimer:
      "Deze site is niet verbonden met of goedgekeurd door DJI. Productnamen en afbeeldingen worden alleen gebruikt ter identificatie.",
  },
  pl: {
    countdownLabel: "Oferta Ograniczona Czasowo",
    heroTitle: "Kompletny zestaw drona DJI w niesamowitej cenie.",
    heroSubtitle:
      "Wraz z premierą nowej globalnej linii starsze zapasy są teraz udostępniane.",
    heroFeatureLine: "TORBA, ŚMIGŁA, OSŁONY, KABLE I BATERIA.",
    ctaGetMyDrone: "ODBIERZ MOJEGO DRONA",
    carouselGoToImage: "Przejdź do obrazu",
    kitImageAlt: "Elementy zestawu DJI Mavic",
    kitTitle: "Co Zawiera Zestaw",
    kitBody:
      "Otrzymujesz kompletny pakiet zaprojektowany tak, aby od razu po wyjęciu z pudełka łatwo rozpocząć lot.",
    kitItemDrone: "Dron DJI Mavic (3 Pro lub 4 Pro)",
    kitItemController: "Inteligentny kontroler",
    kitItemBattery: "1 bateria o długiej żywotności",
    kitItemPropellers: "Dodatkowe śmigła i osłony",
    kitItemCables: "Kable do ładowania",
    kitItemBag: "Torba premium + zintegrowany gimbal",
    comparisonHeadingLead: "Porównanie",
    comparisonHeadingRest: "DJI Mavic 4 Pro i 3 Pro",
    comparisonSubtitle: "Skok nowej generacji w zasięgu i ładowaniu.",
    metricFlightRange: "Zasięg Lotu",
    metricChargingThree: "Czas Ładowania (3 Baterie)",
    metricChargingOne: "Ładowanie (1 Bateria)",
    upTo41Km: "do 41km",
    upTo28Km: "do 28km",
    chooseModelTitle: "Wybierz Model",
    chooseModelSubtitle: "Kompletny zestaw gotowy do lotu. Darmowa wysyłka.",
    productBadge: "Kit Fly More",
    completeKit: "Kompletny Zestaw",
    topicController: "Kontroler",
    topicBag: "Torba",
    topicPropellers: "Śmigła",
    topicGuards: "Osłony",
    topicCables: "Kable",
    topicBattery: "Bateria",
    freeShipping: "Darmowa Wysyłka",
    limitedStock: "Ograniczony Stan",
    faqTitle: "Najczęstsze Pytania",
    faqShippingQ: "Jak długo trwa dostawa?",
    faqShippingA:
      "Wysyłka jest darmowa, a średni czas dostawy wynosi od 7 do 15 dni roboczych, zależnie od lokalizacji.",
    faqPriceQ: "Dlaczego cena jest tak niska?",
    faqPriceA:
      "Wraz z premierą nowej globalnej linii DJI wyprzedawane są zapasy obecnej generacji. Korzystamy z bezpośrednich umów z dystrybutorami, aby oferować ceny poniżej wartości rynkowej.",
    faqReturnQ: "Czy mogę zwrócić produkt, jeśli mi się nie spodoba?",
    faqReturnA:
      "Tak. Masz 30 dni na bezpłatny zwrot produktu i pełny zwrot pieniędzy, bez pytań.",
    faqDifferenceQ: "Jaka jest różnica między Mavic 3 Pro a 4 Pro?",
    faqDifferenceA:
      "Mavic 4 Pro ma zasięg lotu do 41 km (wobec 28 km), ładuje 3 baterie w 90 min (wobec 210 min) i ma ulepszony sensor obrazu o wyższej rozdzielczości.",
    footerSeries: "Seria Mavic Pro",
    privacy: "Prywatność",
    terms: "Warunki",
    contact: "Kontakt",
    disclaimer:
      "Ta strona nie jest powiązana z DJI ani przez DJI zatwierdzona. Nazwy i obrazy produktów służą wyłącznie identyfikacji.",
  },
  sv: {
    countdownLabel: "Tidsbegränsat Erbjudande",
    heroTitle: "Komplett DJI-drönarkit till ett otroligt pris.",
    heroSubtitle:
      "När den nya globala serien lanseras släpps äldre lager nu ut.",
    heroFeatureLine: "VÄSKA, PROPELLRAR, SKYDD, KABLAR OCH BATTERI.",
    ctaGetMyDrone: "HÄMTA MIN DRÖNARE",
    carouselGoToImage: "Gå till bild",
    kitImageAlt: "DJI Mavic-kitdelar",
    kitTitle: "Vad Som Ingår i Kitet",
    kitBody:
      "Du får ett komplett paket som är gjort för att tas ur lådan och flyga enkelt från första användningen.",
    kitItemDrone: "DJI Mavic-drönare (3 Pro eller 4 Pro)",
    kitItemController: "Smart fjärrkontroll",
    kitItemBattery: "1 batteri med lång livslängd",
    kitItemPropellers: "Extra propellrar och skydd",
    kitItemCables: "Laddningskablar",
    kitItemBag: "Premiumväska + integrerad gimbal",
    comparisonHeadingLead: "Jämförelse",
    comparisonHeadingRest: "mellan DJI Mavic 4 Pro och 3 Pro",
    comparisonSubtitle: "Nästa generations språng i räckvidd och laddning.",
    metricFlightRange: "Flygräckvidd",
    metricChargingThree: "Laddningstid (3 Batterier)",
    metricChargingOne: "Laddning (1 Batteri)",
    upTo41Km: "upp till 41km",
    upTo28Km: "upp till 28km",
    chooseModelTitle: "Välj Din Modell",
    chooseModelSubtitle: "Komplett kit redo att flyga. Fri frakt.",
    productBadge: "Kit Fly More",
    completeKit: "Komplett Kit",
    topicController: "Kontroll",
    topicBag: "Väska",
    topicPropellers: "Propellrar",
    topicGuards: "Skydd",
    topicCables: "Kablar",
    topicBattery: "Batteri",
    freeShipping: "Fri Frakt",
    limitedStock: "Begränsat Lager",
    faqTitle: "Vanliga Frågor",
    faqShippingQ: "Hur lång tid tar leveransen?",
    faqShippingA:
      "Frakten är gratis och genomsnittlig leveranstid är 7 till 15 arbetsdagar beroende på din plats.",
    faqPriceQ: "Varför är priset så lågt?",
    faqPriceA:
      "Med lanseringen av DJIs nya globala serie säljs nuvarande lager ut. Vi använder direkta distributörsavtal för att erbjuda priser under marknadsvärde.",
    faqReturnQ: "Kan jag returnera den om jag inte gillar den?",
    faqReturnA:
      "Ja. Du har 30 dagar på dig att returnera produkten utan kostnad och få full återbetalning, utan frågor.",
    faqDifferenceQ: "Vad är skillnaden mellan Mavic 3 Pro och 4 Pro?",
    faqDifferenceA:
      "Mavic 4 Pro har en flygräckvidd på upp till 41 km (jämfört med 28 km), laddar 3 batterier på 90 min (jämfört med 210 min) och har en förbättrad bildsensor med högre upplösning.",
    footerSeries: "Mavic Pro-serien",
    privacy: "Integritet",
    terms: "Villkor",
    contact: "Kontakt",
    disclaimer:
      "Denna webbplats är inte kopplad till eller godkänd av DJI. Produktnamn och bilder används endast för identifiering.",
  },
  tr: {
    countdownLabel: "Sınırlı Süreli Teklif",
    heroTitle: "Eksiksiz DJI drone kiti inanılmaz bir fiyata.",
    heroSubtitle:
      "Yeni küresel seri lansmanıyla birlikte eski stoklar şimdi satışa açılıyor.",
    heroFeatureLine: "ÇANTA, PERVANELER, KORUYUCULAR, KABLOLAR VE BATARYA.",
    ctaGetMyDrone: "DRONE'UMU AL",
    carouselGoToImage: "Görüntüye git",
    kitImageAlt: "DJI Mavic kit parçaları",
    kitTitle: "Kitin İçinde Neler Var",
    kitBody:
      "Kutudan çıkar çıkmaz kolayca uçmanız için tasarlanmış eksiksiz bir paket alırsınız.",
    kitItemDrone: "DJI Mavic Drone (3 Pro veya 4 Pro)",
    kitItemController: "Akıllı uzaktan kumanda",
    kitItemBattery: "1 uzun ömürlü batarya",
    kitItemPropellers: "Ekstra pervaneler ve koruyucular",
    kitItemCables: "Şarj kabloları",
    kitItemBag: "Premium çanta + entegre gimbal",
    comparisonHeadingLead: "Karşılaştırma",
    comparisonHeadingRest: "DJI Mavic 4 Pro ve 3 Pro arasında",
    comparisonSubtitle: "Menzil ve şarjda yeni nesil sıçrama.",
    metricFlightRange: "Uçuş Menzili",
    metricChargingThree: "Şarj Süresi (3 Batarya)",
    metricChargingOne: "Şarj (1 Batarya)",
    upTo41Km: "41km'ye kadar",
    upTo28Km: "28km'ye kadar",
    chooseModelTitle: "Modelinizi Seçin",
    chooseModelSubtitle: "Uçuşa hazır eksiksiz kit. Ücretsiz kargo.",
    productBadge: "Kit Fly More",
    completeKit: "Eksiksiz Kit",
    topicController: "Kumanda",
    topicBag: "Çanta",
    topicPropellers: "Pervaneler",
    topicGuards: "Koruyucular",
    topicCables: "Kablolar",
    topicBattery: "Batarya",
    freeShipping: "Ücretsiz Kargo",
    limitedStock: "Sınırlı Stok",
    faqTitle: "Sık Sorulan Sorular",
    faqShippingQ: "Teslimat ne kadar sürer?",
    faqShippingA:
      "Kargo ücretsizdir ve ortalama teslimat süresi konumunuza bağlı olarak 7 ila 15 iş günüdür.",
    faqPriceQ: "Fiyat neden bu kadar düşük?",
    faqPriceA:
      "DJI'nin yeni küresel serisinin lansmanıyla mevcut nesil stoklar eritiliyor. Piyasa değerinin altında fiyat sunmak için doğrudan distribütör anlaşmaları kullanıyoruz.",
    faqReturnQ: "Beğenmezsem iade edebilir miyim?",
    faqReturnA:
      "Evet. Ürünü ücretsiz iade etmek ve tam geri ödeme almak için 30 gününüz var, soru sorulmaz.",
    faqDifferenceQ: "Mavic 3 Pro ile 4 Pro arasındaki fark nedir?",
    faqDifferenceA:
      "Mavic 4 Pro, 41 km'ye kadar uçuş menziline sahiptir (28 km'ye karşı), 3 bataryayı 90 dakikada şarj eder (210 dakikaya karşı) ve daha yüksek çözünürlüklü geliştirilmiş görüntü sensörü içerir.",
    footerSeries: "Mavic Pro Serisi",
    privacy: "Gizlilik",
    terms: "Şartlar",
    contact: "İletişim",
    disclaimer:
      "Bu site DJI ile bağlantılı değildir ve DJI tarafından onaylanmamıştır. Ürün adları ve görseller yalnızca tanımlama amacıyla kullanılır.",
  },
  ar: {
    countdownLabel: "عرض لفترة محدودة",
    countdownHourShort: "س",
    countdownMinuteShort: "د",
    countdownSecondShort: "ث",
    heroTitle: "طقم درون DJI كامل بسعر مذهل.",
    heroSubtitle:
      "مع إطلاق المجموعة العالمية الجديدة، يتم الآن طرح مخزون الجيل السابق.",
    heroFeatureLine: "حقيبة، مراوح، واقيات، كابلات وبطارية.",
    ctaGetMyDrone: "احصل على الدرون",
    carouselGoToImage: "انتقل إلى الصورة",
    kitImageAlt: "محتويات طقم DJI Mavic",
    kitTitle: "ماذا يوجد داخل الطقم",
    kitBody:
      "تحصل على حزمة كاملة مصممة لتخرج من العلبة وتطير بسهولة من أول استخدام.",
    kitItemDrone: "درون DJI Mavic (3 Pro أو 4 Pro)",
    kitItemController: "جهاز تحكم ذكي",
    kitItemBattery: "بطارية واحدة طويلة العمر",
    kitItemPropellers: "مراوح إضافية وواقيات",
    kitItemCables: "كابلات شحن",
    kitItemBag: "حقيبة فاخرة + جيمبال مدمج",
    comparisonHeadingLead: "مقارنة",
    comparisonHeadingRest: "بين DJI Mavic 4 Pro و 3 Pro",
    comparisonSubtitle: "قفزة الجيل الجديد في المدى والشحن.",
    metricFlightRange: "مدى الطيران",
    metricChargingThree: "وقت الشحن (3 بطاريات)",
    metricChargingOne: "الشحن (بطارية واحدة)",
    upTo41Km: "حتى 41 كم",
    upTo28Km: "حتى 28 كم",
    chooseModelTitle: "اختر الطراز",
    chooseModelSubtitle: "طقم كامل جاهز للطيران. شحن مجاني.",
    productBadge: "Kit Fly More",
    completeKit: "طقم كامل",
    topicController: "وحدة التحكم",
    topicBag: "حقيبة",
    topicPropellers: "مراوح",
    topicGuards: "واقيات",
    topicCables: "كابلات",
    topicBattery: "بطارية",
    freeShipping: "شحن مجاني",
    limitedStock: "مخزون محدود",
    faqTitle: "الأسئلة الشائعة",
    faqShippingQ: "كم يستغرق التوصيل؟",
    faqShippingA:
      "الشحن مجاني ومتوسط مدة التسليم من 7 إلى 15 يوم عمل حسب موقعك.",
    faqPriceQ: "لماذا السعر منخفض جدًا؟",
    faqPriceA:
      "مع إطلاق خط DJI العالمي الجديد، يتم تصفية مخزون الجيل الحالي. نستخدم اتفاقيات مباشرة مع الموزعين لتقديم أسعار أقل من السوق.",
    faqReturnQ: "هل يمكنني الإرجاع إذا لم يعجبني المنتج؟",
    faqReturnA:
      "نعم. لديك 30 يومًا لإرجاع المنتج مجانًا واسترداد المبلغ بالكامل بدون أسئلة.",
    faqDifferenceQ: "ما الفرق بين Mavic 3 Pro و 4 Pro؟",
    faqDifferenceA:
      "يصل مدى Mavic 4 Pro إلى 41 كم (مقابل 28 كم)، ويشحن 3 بطاريات خلال 90 دقيقة (مقابل 210 دقائق)، ويتضمن مستشعر صورة مطورًا بدقة أعلى.",
    footerSeries: "سلسلة Mavic Pro",
    privacy: "الخصوصية",
    terms: "الشروط",
    contact: "اتصال",
    disclaimer:
      "هذا الموقع غير تابع لـ DJI ولا معتمد منها. تُستخدم أسماء المنتجات وصورها لأغراض التعريف فقط.",
  },
  he: {
    countdownLabel: "מבצע לזמן מוגבל",
    countdownHourShort: "ש",
    countdownMinuteShort: "ד",
    countdownSecondShort: "שנ",
    heroTitle: "ערכת רחפן DJI מלאה במחיר מדהים.",
    heroSubtitle:
      "עם השקת הקו הגלובלי החדש, מלאי מהדור הקודם משתחרר כעת.",
    heroFeatureLine: "תיק, מדחפים, מגנים, כבלים וסוללה.",
    ctaGetMyDrone: "קבל את הרחפן שלי",
    carouselGoToImage: "עבור לתמונה",
    kitImageAlt: "פריטי ערכת DJI Mavic",
    kitTitle: "מה כלול בערכה",
    kitBody:
      "אתה מקבל חבילה מלאה שנועדה לצאת מהקופסה ולטוס בקלות כבר מהשימוש הראשון.",
    kitItemDrone: "רחפן DJI Mavic (3 Pro או 4 Pro)",
    kitItemController: "שלט חכם",
    kitItemBattery: "סוללה אחת לטווח ארוך",
    kitItemPropellers: "מדחפים נוספים ומגנים",
    kitItemCables: "כבלי טעינה",
    kitItemBag: "תיק פרימיום + גימבל משולב",
    comparisonHeadingLead: "השוואה",
    comparisonHeadingRest: "בין DJI Mavic 4 Pro ל-3 Pro",
    comparisonSubtitle: "קפיצת דור חדשה בטווח ובטעינה.",
    metricFlightRange: "טווח טיסה",
    metricChargingThree: "זמן טעינה (3 סוללות)",
    metricChargingOne: "טעינה (סוללה אחת)",
    upTo41Km: "עד 41 קמ",
    upTo28Km: "עד 28 קמ",
    chooseModelTitle: "בחר דגם",
    chooseModelSubtitle: "ערכה מלאה מוכנה לטיסה. משלוח חינם.",
    productBadge: "Kit Fly More",
    completeKit: "ערכה מלאה",
    topicController: "שלט",
    topicBag: "תיק",
    topicPropellers: "מדחפים",
    topicGuards: "מגנים",
    topicCables: "כבלים",
    topicBattery: "סוללה",
    freeShipping: "משלוח חינם",
    limitedStock: "מלאי מוגבל",
    faqTitle: "שאלות נפוצות",
    faqShippingQ: "כמה זמן לוקח המשלוח?",
    faqShippingA:
      "המשלוח חינם וזמן ההגעה הממוצע הוא 7 עד 15 ימי עסקים, בהתאם למיקום שלך.",
    faqPriceQ: "למה המחיר כל כך נמוך?",
    faqPriceA:
      "עם השקת הקו הגלובלי החדש של DJI, מלאי הדור הנוכחי נמכר. אנו משתמשים בהסכמים ישירים עם מפיצים כדי להציע מחירים מתחת למחיר השוק.",
    faqReturnQ: "אפשר להחזיר אם לא אהבתי?",
    faqReturnA:
      "כן. יש לך 30 יום להחזיר את המוצר ללא עלות ולקבל החזר מלא, בלי שאלות.",
    faqDifferenceQ: "מה ההבדל בין Mavic 3 Pro ל-4 Pro?",
    faqDifferenceA:
      "ל-Mavic 4 Pro טווח טיסה של עד 41 קמ (לעומת 28 קמ), טעינת 3 סוללות ב-90 דקות (לעומת 210 דקות), וחיישן תמונה משופר ברזולוציה גבוהה יותר.",
    footerSeries: "סדרת Mavic Pro",
    privacy: "פרטיות",
    terms: "תנאים",
    contact: "צור קשר",
    disclaimer:
      "אתר זה אינו מזוהה עם DJI ואינו מאושר על ידה. שמות ותמונות מוצרים משמשים לזיהוי בלבד.",
  },
  ru: {
    countdownLabel: "Предложение Ограничено",
    heroTitle: "Полный комплект дрона DJI по невероятной цене.",
    heroSubtitle:
      "С запуском новой глобальной линейки складские остатки предыдущего поколения теперь распродаются.",
    heroFeatureLine: "СУМКА, ПРОПЕЛЛЕРЫ, ЗАЩИТА, КАБЕЛИ И БАТАРЕЯ.",
    ctaGetMyDrone: "ПОЛУЧИТЬ МОЙ ДРОН",
    carouselGoToImage: "Перейти к изображению",
    kitImageAlt: "Комплект DJI Mavic",
    kitTitle: "Что Входит в Комплект",
    kitBody:
      "Вы получаете полный набор, готовый к простому полету сразу после распаковки.",
    kitItemDrone: "Дрон DJI Mavic (3 Pro или 4 Pro)",
    kitItemController: "Умный пульт управления",
    kitItemBattery: "1 долговечная батарея",
    kitItemPropellers: "Дополнительные пропеллеры и защита",
    kitItemCables: "Зарядные кабели",
    kitItemBag: "Премиальная сумка + встроенный стабилизатор",
    comparisonHeadingLead: "Сравнение",
    comparisonHeadingRest: "DJI Mavic 4 Pro и 3 Pro",
    comparisonSubtitle: "Прыжок нового поколения в дальности и зарядке.",
    metricFlightRange: "Дальность Полета",
    metricChargingThree: "Время Зарядки (3 Батареи)",
    metricChargingOne: "Зарядка (1 Батарея)",
    upTo41Km: "до 41км",
    upTo28Km: "до 28км",
    chooseModelTitle: "Выберите Модель",
    chooseModelSubtitle: "Полный комплект готов к полету. Бесплатная доставка.",
    productBadge: "Kit Fly More",
    completeKit: "Полный Комплект",
    topicController: "Пульт",
    topicBag: "Сумка",
    topicPropellers: "Пропеллеры",
    topicGuards: "Защита",
    topicCables: "Кабели",
    topicBattery: "Батарея",
    freeShipping: "Бесплатная Доставка",
    limitedStock: "Ограниченный Запас",
    faqTitle: "Частые Вопросы",
    faqShippingQ: "Сколько занимает доставка?",
    faqShippingA:
      "Доставка бесплатная, средний срок составляет от 7 до 15 рабочих дней в зависимости от вашего местоположения.",
    faqPriceQ: "Почему цена такая низкая?",
    faqPriceA:
      "С запуском новой глобальной линейки DJI текущие складские остатки распродаются. Мы используем прямые соглашения с дистрибьюторами, чтобы предлагать цены ниже рыночных.",
    faqReturnQ: "Можно ли вернуть товар, если он не понравится?",
    faqReturnA:
      "Да. У вас есть 30 дней, чтобы бесплатно вернуть товар и получить полный возврат средств без вопросов.",
    faqDifferenceQ: "В чем разница между Mavic 3 Pro и 4 Pro?",
    faqDifferenceA:
      "Mavic 4 Pro имеет дальность полета до 41 км (против 28 км), заряжает 3 батареи за 90 мин (против 210 мин) и включает улучшенный датчик изображения с более высоким разрешением.",
    footerSeries: "Серия Mavic Pro",
    privacy: "Конфиденциальность",
    terms: "Условия",
    contact: "Контакты",
    disclaimer:
      "Этот сайт не связан с DJI и не одобрен DJI. Названия и изображения продуктов используются только для идентификации.",
  },
  ja: {
    countdownLabel: "期間限定オファー",
    heroTitle: "DJIドローン完全キットを驚きの価格で。",
    heroSubtitle:
      "新しいグローバルラインの発売に伴い、旧世代の在庫が放出されています。",
    heroFeatureLine: "バッグ、プロペラ、ガード、ケーブル、バッテリー付き。",
    ctaGetMyDrone: "ドローンを入手",
    carouselGoToImage: "画像へ移動",
    kitImageAlt: "DJI Mavicキット内容",
    kitTitle: "キット内容",
    kitBody:
      "箱から出してすぐに簡単に飛ばせるよう設計された完全なセットをお届けします。",
    kitItemDrone: "DJI Mavicドローン（3 Proまたは4 Pro）",
    kitItemController: "スマート送信機",
    kitItemBattery: "長時間バッテリー1個",
    kitItemPropellers: "予備プロペラとガード",
    kitItemCables: "充電ケーブル",
    kitItemBag: "プレミアムバッグ + 内蔵ジンバル",
    comparisonHeadingLead: "比較",
    comparisonHeadingRest: "DJI Mavic 4 Proと3 Pro",
    comparisonSubtitle: "航続距離と充電性能における新世代の進化。",
    metricFlightRange: "飛行距離",
    metricChargingThree: "充電時間（バッテリー3個）",
    metricChargingOne: "充電（バッテリー1個）",
    upTo41Km: "最大41km",
    upTo28Km: "最大28km",
    chooseModelTitle: "モデルを選択",
    chooseModelSubtitle: "すぐに飛ばせる完全キット。送料無料。",
    productBadge: "Kit Fly More",
    completeKit: "完全キット",
    topicController: "送信機",
    topicBag: "バッグ",
    topicPropellers: "プロペラ",
    topicGuards: "ガード",
    topicCables: "ケーブル",
    topicBattery: "バッテリー",
    freeShipping: "送料無料",
    limitedStock: "在庫限定",
    faqTitle: "よくある質問",
    faqShippingQ: "配送にはどのくらいかかりますか？",
    faqShippingA:
      "送料は無料で、平均配送期間は地域により7〜15営業日です。",
    faqPriceQ: "なぜこんなに安いのですか？",
    faqPriceA:
      "DJIの新しいグローバルライン発売に伴い、現行世代の在庫が整理されています。直接の販売契約により市場価格を下回る価格を実現しています。",
    faqReturnQ: "気に入らなければ返品できますか？",
    faqReturnA:
      "はい。30日以内であれば無料で返品でき、全額返金を受けられます。",
    faqDifferenceQ: "Mavic 3 Proと4 Proの違いは何ですか？",
    faqDifferenceA:
      "Mavic 4 Proは最大41kmの飛行距離（28kmに対して）、3個のバッテリーを90分で充電（210分に対して）し、より高解像度の改良型イメージセンサーを搭載しています。",
    footerSeries: "Mavic Proシリーズ",
    privacy: "プライバシー",
    terms: "利用規約",
    contact: "お問い合わせ",
    disclaimer:
      "このサイトはDJIと提携しておらず、DJIの承認を受けていません。製品名と画像は識別目的でのみ使用されています。",
  },
  ko: {
    countdownLabel: "기간 한정 혜택",
    heroTitle: "완전한 DJI 드론 키트를 놀라운 가격에.",
    heroSubtitle:
      "새 글로벌 라인업 출시와 함께 이전 세대 재고가 공개되고 있습니다.",
    heroFeatureLine: "가방, 프로펠러, 가드, 케이블 및 배터리.",
    ctaGetMyDrone: "내 드론 받기",
    carouselGoToImage: "이미지로 이동",
    kitImageAlt: "DJI Mavic 키트 구성품",
    kitTitle: "키트 구성품",
    kitBody:
      "상자에서 꺼내 바로 쉽게 비행할 수 있도록 설계된 완전한 번들을 받게 됩니다.",
    kitItemDrone: "DJI Mavic 드론 (3 Pro 또는 4 Pro)",
    kitItemController: "스마트 조종기",
    kitItemBattery: "장시간 배터리 1개",
    kitItemPropellers: "추가 프로펠러 및 가드",
    kitItemCables: "충전 케이블",
    kitItemBag: "프리미엄 가방 + 통합 짐벌",
    comparisonHeadingLead: "비교",
    comparisonHeadingRest: "DJI Mavic 4 Pro와 3 Pro",
    comparisonSubtitle: "거리와 충전에서 보여주는 차세대 도약.",
    metricFlightRange: "비행 거리",
    metricChargingThree: "충전 시간 (배터리 3개)",
    metricChargingOne: "충전 (배터리 1개)",
    upTo41Km: "최대 41km",
    upTo28Km: "최대 28km",
    chooseModelTitle: "모델 선택",
    chooseModelSubtitle: "비행 준비가 된 완전 키트. 무료 배송.",
    productBadge: "Kit Fly More",
    completeKit: "완전 키트",
    topicController: "조종기",
    topicBag: "가방",
    topicPropellers: "프로펠러",
    topicGuards: "가드",
    topicCables: "케이블",
    topicBattery: "배터리",
    freeShipping: "무료 배송",
    limitedStock: "한정 재고",
    faqTitle: "자주 묻는 질문",
    faqShippingQ: "배송은 얼마나 걸리나요?",
    faqShippingA:
      "배송은 무료이며 평균 배송 기간은 위치에 따라 영업일 기준 7~15일입니다.",
    faqPriceQ: "가격이 왜 이렇게 낮나요?",
    faqPriceA:
      "DJI의 새로운 글로벌 라인업 출시로 현재 세대 재고가 정리되고 있습니다. 직접 유통 계약을 통해 시장가보다 낮은 가격을 제공합니다.",
    faqReturnQ: "마음에 들지 않으면 반품할 수 있나요?",
    faqReturnA:
      "예. 30일 이내에 무료로 반품하고 전액 환불받을 수 있습니다.",
    faqDifferenceQ: "Mavic 3 Pro와 4 Pro의 차이는 무엇인가요?",
    faqDifferenceA:
      "Mavic 4 Pro는 최대 41km 비행 거리(28km 대비), 3개 배터리 90분 충전(210분 대비), 더 높은 해상도의 향상된 이미지 센서를 제공합니다.",
    footerSeries: "Mavic Pro 시리즈",
    privacy: "개인정보",
    terms: "약관",
    contact: "문의",
    disclaimer:
      "이 사이트는 DJI와 제휴하거나 DJI의 승인을 받은 사이트가 아닙니다. 제품명과 이미지는 식별 목적으로만 사용됩니다.",
  },
  "zh-Hans": {
    countdownLabel: "限时优惠",
    heroTitle: "完整 DJI 无人机套装，惊喜价格。",
    heroSubtitle: "随着全新全球产品线发布，上一代库存现正释放。",
    heroFeatureLine: "收纳包、螺旋桨、保护罩、线缆和电池。",
    ctaGetMyDrone: "获取我的无人机",
    carouselGoToImage: "前往图片",
    kitImageAlt: "DJI Mavic 套装配件",
    kitTitle: "套装包含什么",
    kitBody: "你将收到完整套装，开箱即可轻松起飞。",
    kitItemDrone: "DJI Mavic 无人机（3 Pro 或 4 Pro）",
    kitItemController: "智能遥控器",
    kitItemBattery: "1 块长续航电池",
    kitItemPropellers: "备用螺旋桨和保护罩",
    kitItemCables: "充电线",
    kitItemBag: "高级收纳包 + 集成云台",
    comparisonHeadingLead: "对比",
    comparisonHeadingRest: "DJI Mavic 4 Pro 与 3 Pro",
    comparisonSubtitle: "新一代在航程和充电方面的跃升。",
    metricFlightRange: "飞行距离",
    metricChargingThree: "充电时间（3块电池）",
    metricChargingOne: "充电（1块电池）",
    upTo41Km: "最高 41km",
    upTo28Km: "最高 28km",
    chooseModelTitle: "选择你的型号",
    chooseModelSubtitle: "完整套装，即刻起飞。免费配送。",
    productBadge: "Kit Fly More",
    completeKit: "完整套装",
    topicController: "遥控器",
    topicBag: "收纳包",
    topicPropellers: "螺旋桨",
    topicGuards: "保护罩",
    topicCables: "线缆",
    topicBattery: "电池",
    freeShipping: "免费配送",
    limitedStock: "库存有限",
    faqTitle: "常见问题",
    faqShippingQ: "配送需要多久？",
    faqShippingA: "配送免费，平均送达时间为7至15个工作日，具体取决于你的位置。",
    faqPriceQ: "为什么价格这么低？",
    faqPriceA:
      "随着 DJI 全新全球产品线发布，当前一代库存正在清仓。我们通过直接分销协议提供低于市场价的价格。",
    faqReturnQ: "如果不喜欢可以退货吗？",
    faqReturnA: "可以。你有30天时间免费退货并获得全额退款，无需说明理由。",
    faqDifferenceQ: "Mavic 3 Pro 和 4 Pro 有什么区别？",
    faqDifferenceA:
      "Mavic 4 Pro 飞行距离最高41公里（对比28公里），3块电池90分钟充满（对比210分钟），并配备更高分辨率的升级影像传感器。",
    footerSeries: "Mavic Pro 系列",
    privacy: "隐私",
    terms: "条款",
    contact: "联系",
    disclaimer:
      "本网站与 DJI 无关联，也未获得 DJI 背书。产品名称和图片仅用于识别目的。",
  },
  "zh-Hant": {
    countdownLabel: "限時優惠",
    heroTitle: "完整 DJI 無人機套裝，驚喜價格。",
    heroSubtitle: "隨著全新全球產品線發布，上一代庫存現正釋出。",
    heroFeatureLine: "收納包、螺旋槳、保護罩、線材和電池。",
    ctaGetMyDrone: "取得我的無人機",
    carouselGoToImage: "前往圖片",
    kitImageAlt: "DJI Mavic 套裝配件",
    kitTitle: "套裝包含內容",
    kitBody: "你將收到完整套裝，開箱即可輕鬆起飛。",
    kitItemDrone: "DJI Mavic 無人機（3 Pro 或 4 Pro）",
    kitItemController: "智慧遙控器",
    kitItemBattery: "1 顆長效電池",
    kitItemPropellers: "備用螺旋槳和保護罩",
    kitItemCables: "充電線",
    kitItemBag: "高級收納包 + 整合雲台",
    comparisonHeadingLead: "比較",
    comparisonHeadingRest: "DJI Mavic 4 Pro 與 3 Pro",
    comparisonSubtitle: "新世代在航程與充電上的躍升。",
    metricFlightRange: "飛行距離",
    metricChargingThree: "充電時間（3顆電池）",
    metricChargingOne: "充電（1顆電池）",
    upTo41Km: "最高 41km",
    upTo28Km: "最高 28km",
    chooseModelTitle: "選擇你的型號",
    chooseModelSubtitle: "完整套裝，即刻起飛。免費配送。",
    productBadge: "Kit Fly More",
    completeKit: "完整套裝",
    topicController: "遙控器",
    topicBag: "收納包",
    topicPropellers: "螺旋槳",
    topicGuards: "保護罩",
    topicCables: "線材",
    topicBattery: "電池",
    freeShipping: "免費配送",
    limitedStock: "庫存有限",
    faqTitle: "常見問題",
    faqShippingQ: "配送需要多久？",
    faqShippingA: "配送免費，平均送達時間為7至15個工作天，視你的所在地而定。",
    faqPriceQ: "為什麼價格這麼低？",
    faqPriceA:
      "隨著 DJI 全新全球產品線發布，現有世代庫存正在出清。我們透過直接經銷協議提供低於市場價的價格。",
    faqReturnQ: "如果不喜歡可以退貨嗎？",
    faqReturnA: "可以。你有30天可免費退貨並獲得全額退款，無需說明理由。",
    faqDifferenceQ: "Mavic 3 Pro 和 4 Pro 有什麼不同？",
    faqDifferenceA:
      "Mavic 4 Pro 飛行距離最高41公里（相較28公里），3顆電池90分鐘充滿（相較210分鐘），並配備解析度更高的升級影像感測器。",
    footerSeries: "Mavic Pro 系列",
    privacy: "隱私",
    terms: "條款",
    contact: "聯絡",
    disclaimer:
      "本網站與 DJI 無關，亦未獲 DJI 背書。產品名稱與圖片僅供識別用途。",
  },
  hi: {
    countdownLabel: "सीमित समय का ऑफर",
    heroTitle: "पूरा DJI ड्रोन किट शानदार कीमत पर।",
    heroSubtitle:
      "नई वैश्विक लाइनअप के लॉन्च के साथ पुराना स्टॉक अब जारी किया जा रहा है।",
    heroFeatureLine: "बैग, प्रोपेलर, गार्ड, केबल और बैटरी.",
    ctaGetMyDrone: "मेरा ड्रोन लें",
    carouselGoToImage: "छवि पर जाएं",
    kitImageAlt: "DJI Mavic किट आइटम",
    kitTitle: "किट में क्या शामिल है",
    kitBody:
      "आपको एक पूरा बंडल मिलता है जिसे बॉक्स से निकालते ही आसानी से उड़ाने के लिए बनाया गया है।",
    kitItemDrone: "DJI Mavic ड्रोन (3 Pro या 4 Pro)",
    kitItemController: "स्मार्ट रिमोट कंट्रोलर",
    kitItemBattery: "1 लंबी अवधि की बैटरी",
    kitItemPropellers: "अतिरिक्त प्रोपेलर और गार्ड",
    kitItemCables: "चार्जिंग केबल",
    kitItemBag: "प्रीमियम बैग + इंटीग्रेटेड गिम्बल",
    comparisonHeadingLead: "तुलना",
    comparisonHeadingRest: "DJI Mavic 4 Pro और 3 Pro के बीच",
    comparisonSubtitle: "रेंज और चार्जिंग में नई पीढ़ी की छलांग।",
    metricFlightRange: "फ्लाइट रेंज",
    metricChargingThree: "चार्जिंग समय (3 बैटरी)",
    metricChargingOne: "चार्जिंग (1 बैटरी)",
    upTo41Km: "41km तक",
    upTo28Km: "28km तक",
    chooseModelTitle: "अपना मॉडल चुनें",
    chooseModelSubtitle: "उड़ान के लिए तैयार पूरा किट। मुफ्त शिपिंग।",
    productBadge: "Kit Fly More",
    completeKit: "पूरा किट",
    topicController: "कंट्रोलर",
    topicBag: "बैग",
    topicPropellers: "प्रोपेलर",
    topicGuards: "गार्ड",
    topicCables: "केबल",
    topicBattery: "बैटरी",
    freeShipping: "मुफ्त शिपिंग",
    limitedStock: "सीमित स्टॉक",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faqShippingQ: "डिलीवरी में कितना समय लगता है?",
    faqShippingA:
      "शिपिंग मुफ्त है और औसत डिलीवरी समय आपकी लोकेशन के आधार पर 7 से 15 कार्य दिवस है।",
    faqPriceQ: "कीमत इतनी कम क्यों है?",
    faqPriceA:
      "DJI की नई वैश्विक लाइनअप के लॉन्च के साथ वर्तमान पीढ़ी का स्टॉक साफ किया जा रहा है। हम बाजार मूल्य से कम कीमत देने के लिए सीधे वितरक समझौतों का उपयोग करते हैं।",
    faqReturnQ: "अगर मुझे पसंद न आए तो क्या मैं लौट सकता हूं?",
    faqReturnA:
      "हां। आपके पास उत्पाद को बिना लागत लौटाने और पूरा रिफंड पाने के लिए 30 दिन हैं।",
    faqDifferenceQ: "Mavic 3 Pro और 4 Pro में क्या अंतर है?",
    faqDifferenceA:
      "Mavic 4 Pro की उड़ान रेंज 41 km तक है (28 km की तुलना में), यह 3 बैटरी को 90 मिनट में चार्ज करता है (210 मिनट की तुलना में), और उच्च रिज़ॉल्यूशन वाला बेहतर इमेज सेंसर शामिल करता है।",
    footerSeries: "Mavic Pro सीरीज",
    privacy: "गोपनीयता",
    terms: "शर्तें",
    contact: "संपर्क",
    disclaimer:
      "यह साइट DJI से संबद्ध या समर्थित नहीं है। उत्पाद नाम और छवियां केवल पहचान के उद्देश्य से उपयोग की जाती हैं।",
  },
  id: {
    countdownLabel: "Penawaran Waktu Terbatas",
    heroTitle: "Kit drone DJI lengkap dengan harga luar biasa.",
    heroSubtitle:
      "Dengan peluncuran lini global baru, stok generasi sebelumnya kini dirilis.",
    heroFeatureLine: "TAS, BALING-BALING, PELINDUNG, KABEL, DAN BATERAI.",
    ctaGetMyDrone: "DAPATKAN DRONE SAYA",
    carouselGoToImage: "Buka gambar",
    kitImageAlt: "Item kit DJI Mavic",
    kitTitle: "Isi di Dalam Kit",
    kitBody:
      "Anda menerima bundel lengkap yang siap keluar dari kotak dan mudah diterbangkan sejak penggunaan pertama.",
    kitItemDrone: "Drone DJI Mavic (3 Pro atau 4 Pro)",
    kitItemController: "Pengendali jarak jauh pintar",
    kitItemBattery: "1 baterai tahan lama",
    kitItemPropellers: "Baling-baling ekstra dan pelindung",
    kitItemCables: "Kabel pengisian daya",
    kitItemBag: "Tas premium + gimbal terintegrasi",
    comparisonHeadingLead: "Perbandingan",
    comparisonHeadingRest: "antara DJI Mavic 4 Pro dan 3 Pro",
    comparisonSubtitle: "Lompatan generasi baru dalam jangkauan dan pengisian.",
    metricFlightRange: "Jangkauan Terbang",
    metricChargingThree: "Waktu Pengisian (3 Baterai)",
    metricChargingOne: "Pengisian (1 Baterai)",
    upTo41Km: "hingga 41km",
    upTo28Km: "hingga 28km",
    chooseModelTitle: "Pilih Model Anda",
    chooseModelSubtitle: "Kit lengkap siap terbang. Gratis ongkir.",
    productBadge: "Kit Fly More",
    completeKit: "Kit Lengkap",
    topicController: "Kontroler",
    topicBag: "Tas",
    topicPropellers: "Baling-baling",
    topicGuards: "Pelindung",
    topicCables: "Kabel",
    topicBattery: "Baterai",
    freeShipping: "Gratis Ongkir",
    limitedStock: "Stok Terbatas",
    faqTitle: "Pertanyaan Umum",
    faqShippingQ: "Berapa lama pengiriman?",
    faqShippingA:
      "Pengiriman gratis dan rata-rata waktu tiba adalah 7 hingga 15 hari kerja, tergantung lokasi Anda.",
    faqPriceQ: "Mengapa harganya sangat rendah?",
    faqPriceA:
      "Dengan peluncuran lini global baru DJI, stok generasi saat ini sedang dibersihkan. Kami menggunakan perjanjian distributor langsung untuk menawarkan harga di bawah nilai pasar.",
    faqReturnQ: "Bisakah saya mengembalikan jika tidak suka?",
    faqReturnA:
      "Ya. Anda memiliki 30 hari untuk mengembalikan produk tanpa biaya dan menerima pengembalian dana penuh, tanpa pertanyaan.",
    faqDifferenceQ: "Apa perbedaan antara Mavic 3 Pro dan 4 Pro?",
    faqDifferenceA:
      "Mavic 4 Pro memiliki jangkauan terbang hingga 41 km (dibanding 28 km), mengisi 3 baterai dalam 90 menit (dibanding 210 menit), dan menyertakan sensor gambar yang ditingkatkan dengan resolusi lebih tinggi.",
    footerSeries: "Seri Mavic Pro",
    privacy: "Privasi",
    terms: "Syarat",
    contact: "Kontak",
    disclaimer:
      "Situs ini tidak berafiliasi atau didukung oleh DJI. Nama dan gambar produk digunakan hanya untuk tujuan identifikasi.",
  },
};

export function isSupportedLocale(locale: string): locale is SupportedLocale {
  return supportedLocales.includes(locale as SupportedLocale);
}

export function isRtlLocale(locale: string) {
  return rtlLocales.includes(locale as (typeof rtlLocales)[number]);
}

export function getLocalizedCopy(locale: string): Record<string, string> {
  const normalizedLocale = isSupportedLocale(locale) ? locale : "en";
  return {
    ...enCopy,
    ...(localeOverrides[normalizedLocale] ?? {}),
  };
}
